ERROR - 2025-04-30 16:15:53 --> Error connecting to the database: mysqli_sql_exception: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée in C:\Users\Hatim\DevOps_Project\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\Users\Hatim\DevOps_Project\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'devops_tp', 3306, '', 0)
#1 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\Hatim\DevOps_Project\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `db...', Array, false)
#4 C:\Users\Hatim\DevOps_Project\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\Users\Hatim\DevOps_Project\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\Users\Hatim\DevOps_Project\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\Users\Hatim\DevOps_Project\tests\unit\LigneFactureModelTest.php(21): CodeIgniter\Model->insert(Array)
#8 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): Tests\LigneFactureModelTest->testInsertAndFind()
#9 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#10 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#11 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(Tests\LigneFactureModelTest))
#12 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#13 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#14 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#15 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#16 C:\Users\Hatim\DevOps_Project\vendor\bin\phpunit(122): include('C:\\Users\\Hatim\\...')
#17 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée in C:\Users\Hatim\DevOps_Project\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\Hatim\DevOps_Project\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `db...', Array, false)
#3 C:\Users\Hatim\DevOps_Project\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\Users\Hatim\DevOps_Project\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#5 C:\Users\Hatim\DevOps_Project\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\Users\Hatim\DevOps_Project\tests\unit\LigneFactureModelTest.php(21): CodeIgniter\Model->insert(Array)
#7 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): Tests\LigneFactureModelTest->testInsertAndFind()
#8 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#9 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#10 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(Tests\LigneFactureModelTest))
#11 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#12 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#13 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#14 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#15 C:\Users\Hatim\DevOps_Project\vendor\bin\phpunit(122): include('C:\\Users\\Hatim\\...')
#16 {main}
ERROR - 2025-04-30 16:15:57 --> Error connecting to the database: mysqli_sql_exception: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée in C:\Users\Hatim\DevOps_Project\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\Users\Hatim\DevOps_Project\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'devops_tp', 3306, '', 0)
#1 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\Hatim\DevOps_Project\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\Hatim\DevOps_Project\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\Hatim\DevOps_Project\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\Users\Hatim\DevOps_Project\app\Models\LigneFactureModel.php(22): CodeIgniter\BaseModel->findAll()
#7 C:\Users\Hatim\DevOps_Project\tests\unit\LigneFactureModelTest.php(34): App\Models\LigneFactureModel->getByFacture(1)
#8 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): Tests\LigneFactureModelTest->testGetByFacture()
#9 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#10 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#11 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(Tests\LigneFactureModelTest))
#12 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#13 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#14 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#15 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#16 C:\Users\Hatim\DevOps_Project\vendor\bin\phpunit(122): include('C:\\Users\\Hatim\\...')
#17 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée in C:\Users\Hatim\DevOps_Project\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\Hatim\DevOps_Project\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\Users\Hatim\DevOps_Project\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 C:\Users\Hatim\DevOps_Project\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\Users\Hatim\DevOps_Project\app\Models\LigneFactureModel.php(22): CodeIgniter\BaseModel->findAll()
#6 C:\Users\Hatim\DevOps_Project\tests\unit\LigneFactureModelTest.php(34): App\Models\LigneFactureModel->getByFacture(1)
#7 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): Tests\LigneFactureModelTest->testGetByFacture()
#8 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#9 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#10 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(Tests\LigneFactureModelTest))
#11 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#12 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#13 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#14 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#15 C:\Users\Hatim\DevOps_Project\vendor\bin\phpunit(122): include('C:\\Users\\Hatim\\...')
#16 {main}
ERROR - 2025-04-30 16:16:01 --> Error connecting to the database: mysqli_sql_exception: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée in C:\Users\Hatim\DevOps_Project\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\Users\Hatim\DevOps_Project\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'devops_tp', 3306, '', 0)
#1 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\Hatim\DevOps_Project\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\Hatim\DevOps_Project\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\Hatim\DevOps_Project\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\Users\Hatim\DevOps_Project\app\Models\LigneFactureModel.php(28): CodeIgniter\BaseModel->findAll()
#7 C:\Users\Hatim\DevOps_Project\tests\unit\LigneFactureModelTest.php(44): App\Models\LigneFactureModel->getByProduit(2)
#8 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): Tests\LigneFactureModelTest->testGetByProduit()
#9 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#10 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#11 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(Tests\LigneFactureModelTest))
#12 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#13 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#14 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#15 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#16 C:\Users\Hatim\DevOps_Project\vendor\bin\phpunit(122): include('C:\\Users\\Hatim\\...')
#17 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée in C:\Users\Hatim\DevOps_Project\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\Hatim\DevOps_Project\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\Users\Hatim\DevOps_Project\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 C:\Users\Hatim\DevOps_Project\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\Users\Hatim\DevOps_Project\app\Models\LigneFactureModel.php(28): CodeIgniter\BaseModel->findAll()
#6 C:\Users\Hatim\DevOps_Project\tests\unit\LigneFactureModelTest.php(44): App\Models\LigneFactureModel->getByProduit(2)
#7 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): Tests\LigneFactureModelTest->testGetByProduit()
#8 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#9 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#10 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(Tests\LigneFactureModelTest))
#11 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#12 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#13 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#14 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#15 C:\Users\Hatim\DevOps_Project\vendor\bin\phpunit(122): include('C:\\Users\\Hatim\\...')
#16 {main}
ERROR - 2025-04-30 16:16:06 --> Error connecting to the database: mysqli_sql_exception: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée in C:\Users\Hatim\DevOps_Project\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\Users\Hatim\DevOps_Project\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'devops_tp', 3306, '', 0)
#1 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\Hatim\DevOps_Project\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `db...', Array, false)
#4 C:\Users\Hatim\DevOps_Project\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\Users\Hatim\DevOps_Project\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\Users\Hatim\DevOps_Project\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\Users\Hatim\DevOps_Project\tests\unit\LigneFactureModelTest.php(60): CodeIgniter\Model->insert(Array)
#8 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): Tests\LigneFactureModelTest->testUpdateQuantite()
#9 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#10 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#11 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(Tests\LigneFactureModelTest))
#12 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#13 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#14 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#15 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#16 C:\Users\Hatim\DevOps_Project\vendor\bin\phpunit(122): include('C:\\Users\\Hatim\\...')
#17 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée in C:\Users\Hatim\DevOps_Project\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\Hatim\DevOps_Project\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `db...', Array, false)
#3 C:\Users\Hatim\DevOps_Project\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\Users\Hatim\DevOps_Project\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#5 C:\Users\Hatim\DevOps_Project\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\Users\Hatim\DevOps_Project\tests\unit\LigneFactureModelTest.php(60): CodeIgniter\Model->insert(Array)
#7 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): Tests\LigneFactureModelTest->testUpdateQuantite()
#8 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#9 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#10 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(Tests\LigneFactureModelTest))
#11 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#12 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#13 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#14 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#15 C:\Users\Hatim\DevOps_Project\vendor\bin\phpunit(122): include('C:\\Users\\Hatim\\...')
#16 {main}
ERROR - 2025-04-30 16:21:54 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'devops_tp' in C:\Users\Hatim\DevOps_Project\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\Users\Hatim\DevOps_Project\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'devops_tp', 3306, '', 0)
#1 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\Hatim\DevOps_Project\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `db...', Array, false)
#4 C:\Users\Hatim\DevOps_Project\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\Users\Hatim\DevOps_Project\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\Users\Hatim\DevOps_Project\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\Users\Hatim\DevOps_Project\tests\unit\LigneFactureModelTest.php(20): CodeIgniter\Model->insert(Array)
#8 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): Tests\LigneFactureModelTest->testInsertAndFind()
#9 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#10 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#11 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(Tests\LigneFactureModelTest))
#12 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#13 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#14 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#15 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#16 C:\Users\Hatim\DevOps_Project\vendor\bin\phpunit(122): include('C:\\Users\\Hatim\\...')
#17 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'devops_tp' in C:\Users\Hatim\DevOps_Project\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\Hatim\DevOps_Project\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `db...', Array, false)
#3 C:\Users\Hatim\DevOps_Project\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\Users\Hatim\DevOps_Project\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#5 C:\Users\Hatim\DevOps_Project\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\Users\Hatim\DevOps_Project\tests\unit\LigneFactureModelTest.php(20): CodeIgniter\Model->insert(Array)
#7 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): Tests\LigneFactureModelTest->testInsertAndFind()
#8 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#9 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#10 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(Tests\LigneFactureModelTest))
#11 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#12 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#13 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#14 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#15 C:\Users\Hatim\DevOps_Project\vendor\bin\phpunit(122): include('C:\\Users\\Hatim\\...')
#16 {main}
ERROR - 2025-04-30 16:21:54 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'devops_tp' in C:\Users\Hatim\DevOps_Project\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\Users\Hatim\DevOps_Project\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'devops_tp', 3306, '', 0)
#1 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\Hatim\DevOps_Project\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `db...', Array, false)
#4 C:\Users\Hatim\DevOps_Project\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\Users\Hatim\DevOps_Project\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\Users\Hatim\DevOps_Project\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\Users\Hatim\DevOps_Project\tests\unit\LigneFactureModelTest.php(35): CodeIgniter\Model->insert(Array)
#8 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): Tests\LigneFactureModelTest->testGetByArticle()
#9 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#10 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#11 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(Tests\LigneFactureModelTest))
#12 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#13 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#14 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#15 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#16 C:\Users\Hatim\DevOps_Project\vendor\bin\phpunit(122): include('C:\\Users\\Hatim\\...')
#17 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'devops_tp' in C:\Users\Hatim\DevOps_Project\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\Hatim\DevOps_Project\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `db...', Array, false)
#3 C:\Users\Hatim\DevOps_Project\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\Users\Hatim\DevOps_Project\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#5 C:\Users\Hatim\DevOps_Project\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\Users\Hatim\DevOps_Project\tests\unit\LigneFactureModelTest.php(35): CodeIgniter\Model->insert(Array)
#7 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): Tests\LigneFactureModelTest->testGetByArticle()
#8 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#9 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#10 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(Tests\LigneFactureModelTest))
#11 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#12 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#13 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#14 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#15 C:\Users\Hatim\DevOps_Project\vendor\bin\phpunit(122): include('C:\\Users\\Hatim\\...')
#16 {main}
ERROR - 2025-04-30 16:21:54 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'devops_tp' in C:\Users\Hatim\DevOps_Project\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\Users\Hatim\DevOps_Project\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'devops_tp', 3306, '', 0)
#1 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\Hatim\DevOps_Project\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `db...', Array, false)
#4 C:\Users\Hatim\DevOps_Project\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\Users\Hatim\DevOps_Project\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\Users\Hatim\DevOps_Project\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\Users\Hatim\DevOps_Project\tests\unit\LigneFactureModelTest.php(56): CodeIgniter\Model->insert(Array)
#8 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): Tests\LigneFactureModelTest->testUpdateQuantite()
#9 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#10 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#11 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(Tests\LigneFactureModelTest))
#12 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#13 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#14 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#15 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#16 C:\Users\Hatim\DevOps_Project\vendor\bin\phpunit(122): include('C:\\Users\\Hatim\\...')
#17 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'devops_tp' in C:\Users\Hatim\DevOps_Project\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\Hatim\DevOps_Project\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `db...', Array, false)
#3 C:\Users\Hatim\DevOps_Project\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\Users\Hatim\DevOps_Project\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#5 C:\Users\Hatim\DevOps_Project\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\Users\Hatim\DevOps_Project\tests\unit\LigneFactureModelTest.php(56): CodeIgniter\Model->insert(Array)
#7 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): Tests\LigneFactureModelTest->testUpdateQuantite()
#8 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#9 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#10 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(Tests\LigneFactureModelTest))
#11 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#12 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#13 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#14 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#15 C:\Users\Hatim\DevOps_Project\vendor\bin\phpunit(122): include('C:\\Users\\Hatim\\...')
#16 {main}
ERROR - 2025-04-30 16:23:17 --> mysqli_sql_exception: Table 'devops_tp.db_lignefacture' doesn't exist in C:\Users\Hatim\DevOps_Project\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\Users\Hatim\DevOps_Project\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `db...', 0)
#1 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `db...')
#2 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `db...')
#3 C:\Users\Hatim\DevOps_Project\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `db...', Array, false)
#4 C:\Users\Hatim\DevOps_Project\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\Users\Hatim\DevOps_Project\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\Users\Hatim\DevOps_Project\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\Users\Hatim\DevOps_Project\tests\unit\LigneFactureModelTest.php(20): CodeIgniter\Model->insert(Array)
#8 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): Tests\LigneFactureModelTest->testInsertAndFind()
#9 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#10 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#11 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(Tests\LigneFactureModelTest))
#12 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#13 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#14 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#15 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#16 C:\Users\Hatim\DevOps_Project\vendor\bin\phpunit(122): include('C:\\Users\\Hatim\\...')
#17 {main}
ERROR - 2025-04-30 16:23:18 --> mysqli_sql_exception: Table 'devops_tp.db_lignefacture' doesn't exist in C:\Users\Hatim\DevOps_Project\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\Users\Hatim\DevOps_Project\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `db...', 0)
#1 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `db...')
#2 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `db...')
#3 C:\Users\Hatim\DevOps_Project\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `db...', Array, false)
#4 C:\Users\Hatim\DevOps_Project\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\Users\Hatim\DevOps_Project\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\Users\Hatim\DevOps_Project\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\Users\Hatim\DevOps_Project\tests\unit\LigneFactureModelTest.php(35): CodeIgniter\Model->insert(Array)
#8 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): Tests\LigneFactureModelTest->testGetByArticle()
#9 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#10 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#11 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(Tests\LigneFactureModelTest))
#12 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#13 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#14 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#15 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#16 C:\Users\Hatim\DevOps_Project\vendor\bin\phpunit(122): include('C:\\Users\\Hatim\\...')
#17 {main}
ERROR - 2025-04-30 16:23:18 --> mysqli_sql_exception: Table 'devops_tp.db_lignefacture' doesn't exist in C:\Users\Hatim\DevOps_Project\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\Users\Hatim\DevOps_Project\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `db...', 0)
#1 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `db...')
#2 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `db...')
#3 C:\Users\Hatim\DevOps_Project\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `db...', Array, false)
#4 C:\Users\Hatim\DevOps_Project\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\Users\Hatim\DevOps_Project\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\Users\Hatim\DevOps_Project\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\Users\Hatim\DevOps_Project\tests\unit\LigneFactureModelTest.php(56): CodeIgniter\Model->insert(Array)
#8 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): Tests\LigneFactureModelTest->testUpdateQuantite()
#9 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#10 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#11 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(Tests\LigneFactureModelTest))
#12 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#13 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#14 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#15 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#16 C:\Users\Hatim\DevOps_Project\vendor\bin\phpunit(122): include('C:\\Users\\Hatim\\...')
#17 {main}
ERROR - 2025-04-30 16:26:21 --> Error connecting to the database: mysqli_sql_exception: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée in C:\Users\Hatim\DevOps_Project\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\Users\Hatim\DevOps_Project\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'devops_tp', 3306, '', 0)
#1 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\Hatim\DevOps_Project\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `db...', Array, false)
#4 C:\Users\Hatim\DevOps_Project\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\Users\Hatim\DevOps_Project\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\Users\Hatim\DevOps_Project\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\Users\Hatim\DevOps_Project\tests\unit\LigneFactureModelTest.php(20): CodeIgniter\Model->insert(Array)
#8 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): Tests\LigneFactureModelTest->testInsertAndFind()
#9 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#10 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#11 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(Tests\LigneFactureModelTest))
#12 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#13 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#14 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#15 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#16 C:\Users\Hatim\DevOps_Project\vendor\bin\phpunit(122): include('C:\\Users\\Hatim\\...')
#17 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée in C:\Users\Hatim\DevOps_Project\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\Hatim\DevOps_Project\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `db...', Array, false)
#3 C:\Users\Hatim\DevOps_Project\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\Users\Hatim\DevOps_Project\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#5 C:\Users\Hatim\DevOps_Project\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\Users\Hatim\DevOps_Project\tests\unit\LigneFactureModelTest.php(20): CodeIgniter\Model->insert(Array)
#7 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): Tests\LigneFactureModelTest->testInsertAndFind()
#8 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#9 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#10 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(Tests\LigneFactureModelTest))
#11 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#12 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#13 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#14 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#15 C:\Users\Hatim\DevOps_Project\vendor\bin\phpunit(122): include('C:\\Users\\Hatim\\...')
#16 {main}
ERROR - 2025-04-30 16:26:25 --> Error connecting to the database: mysqli_sql_exception: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée in C:\Users\Hatim\DevOps_Project\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\Users\Hatim\DevOps_Project\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'devops_tp', 3306, '', 0)
#1 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\Hatim\DevOps_Project\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `db...', Array, false)
#4 C:\Users\Hatim\DevOps_Project\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\Users\Hatim\DevOps_Project\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\Users\Hatim\DevOps_Project\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\Users\Hatim\DevOps_Project\tests\unit\LigneFactureModelTest.php(35): CodeIgniter\Model->insert(Array)
#8 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): Tests\LigneFactureModelTest->testGetByArticle()
#9 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#10 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#11 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(Tests\LigneFactureModelTest))
#12 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#13 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#14 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#15 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#16 C:\Users\Hatim\DevOps_Project\vendor\bin\phpunit(122): include('C:\\Users\\Hatim\\...')
#17 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée in C:\Users\Hatim\DevOps_Project\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\Hatim\DevOps_Project\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `db...', Array, false)
#3 C:\Users\Hatim\DevOps_Project\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\Users\Hatim\DevOps_Project\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#5 C:\Users\Hatim\DevOps_Project\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\Users\Hatim\DevOps_Project\tests\unit\LigneFactureModelTest.php(35): CodeIgniter\Model->insert(Array)
#7 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): Tests\LigneFactureModelTest->testGetByArticle()
#8 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#9 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#10 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(Tests\LigneFactureModelTest))
#11 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#12 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#13 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#14 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#15 C:\Users\Hatim\DevOps_Project\vendor\bin\phpunit(122): include('C:\\Users\\Hatim\\...')
#16 {main}
ERROR - 2025-04-30 16:26:29 --> Error connecting to the database: mysqli_sql_exception: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée in C:\Users\Hatim\DevOps_Project\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\Users\Hatim\DevOps_Project\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'devops_tp', 3306, '', 0)
#1 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\Hatim\DevOps_Project\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `db...', Array, false)
#4 C:\Users\Hatim\DevOps_Project\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\Users\Hatim\DevOps_Project\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\Users\Hatim\DevOps_Project\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\Users\Hatim\DevOps_Project\tests\unit\LigneFactureModelTest.php(56): CodeIgniter\Model->insert(Array)
#8 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): Tests\LigneFactureModelTest->testUpdateQuantite()
#9 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#10 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#11 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(Tests\LigneFactureModelTest))
#12 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#13 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#14 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#15 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#16 C:\Users\Hatim\DevOps_Project\vendor\bin\phpunit(122): include('C:\\Users\\Hatim\\...')
#17 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée in C:\Users\Hatim\DevOps_Project\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\Hatim\DevOps_Project\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `db...', Array, false)
#3 C:\Users\Hatim\DevOps_Project\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\Users\Hatim\DevOps_Project\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#5 C:\Users\Hatim\DevOps_Project\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\Users\Hatim\DevOps_Project\tests\unit\LigneFactureModelTest.php(56): CodeIgniter\Model->insert(Array)
#7 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): Tests\LigneFactureModelTest->testUpdateQuantite()
#8 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#9 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#10 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(Tests\LigneFactureModelTest))
#11 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#12 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#13 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#14 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#15 C:\Users\Hatim\DevOps_Project\vendor\bin\phpunit(122): include('C:\\Users\\Hatim\\...')
#16 {main}
ERROR - 2025-04-30 17:10:49 --> mysqli_sql_exception: Table 'devops_tp.db_lignefacture' doesn't exist in C:\Users\Hatim\DevOps_Project\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\Users\Hatim\DevOps_Project\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `db...', 0)
#1 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `db...')
#2 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `db...')
#3 C:\Users\Hatim\DevOps_Project\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `db...', Array, false)
#4 C:\Users\Hatim\DevOps_Project\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\Users\Hatim\DevOps_Project\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\Users\Hatim\DevOps_Project\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\Users\Hatim\DevOps_Project\tests\unit\LigneFactureModelTest.php(20): CodeIgniter\Model->insert(Array)
#8 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): Tests\LigneFactureModelTest->testInsertAndFind()
#9 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#10 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#11 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(Tests\LigneFactureModelTest))
#12 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#13 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#14 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#15 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#16 C:\Users\Hatim\DevOps_Project\vendor\bin\phpunit(122): include('C:\\Users\\Hatim\\...')
#17 {main}
ERROR - 2025-04-30 17:10:50 --> mysqli_sql_exception: Table 'devops_tp.db_lignefacture' doesn't exist in C:\Users\Hatim\DevOps_Project\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\Users\Hatim\DevOps_Project\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `db...', 0)
#1 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `db...')
#2 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `db...')
#3 C:\Users\Hatim\DevOps_Project\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `db...', Array, false)
#4 C:\Users\Hatim\DevOps_Project\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\Users\Hatim\DevOps_Project\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\Users\Hatim\DevOps_Project\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\Users\Hatim\DevOps_Project\tests\unit\LigneFactureModelTest.php(35): CodeIgniter\Model->insert(Array)
#8 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): Tests\LigneFactureModelTest->testGetByArticle()
#9 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#10 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#11 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(Tests\LigneFactureModelTest))
#12 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#13 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#14 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#15 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#16 C:\Users\Hatim\DevOps_Project\vendor\bin\phpunit(122): include('C:\\Users\\Hatim\\...')
#17 {main}
ERROR - 2025-04-30 17:10:50 --> mysqli_sql_exception: Table 'devops_tp.db_lignefacture' doesn't exist in C:\Users\Hatim\DevOps_Project\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\Users\Hatim\DevOps_Project\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `db...', 0)
#1 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `db...')
#2 C:\Users\Hatim\DevOps_Project\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `db...')
#3 C:\Users\Hatim\DevOps_Project\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `db...', Array, false)
#4 C:\Users\Hatim\DevOps_Project\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\Users\Hatim\DevOps_Project\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\Users\Hatim\DevOps_Project\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\Users\Hatim\DevOps_Project\tests\unit\LigneFactureModelTest.php(56): CodeIgniter\Model->insert(Array)
#8 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): Tests\LigneFactureModelTest->testUpdateQuantite()
#9 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#10 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#11 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(Tests\LigneFactureModelTest))
#12 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#13 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#14 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#15 C:\Users\Hatim\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#16 C:\Users\Hatim\DevOps_Project\vendor\bin\phpunit(122): include('C:\\Users\\Hatim\\...')
#17 {main}
