ERROR - 2025-04-25 17:40:56 --> Exception: Unable to prepare statement: 1, no such table: db_user in C:\xampp\htdocs\DevOps_Project\system\Database\SQLite3\Connection.php:176
Stack trace:
#0 C:\xampp\htdocs\DevOps_Project\system\Database\SQLite3\Connection.php(176): SQLite3->query('SELECT *\nFROM `...')
#1 C:\xampp\htdocs\DevOps_Project\system\Database\BaseConnection.php(738): CodeIgniter\Database\SQLite3\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\DevOps_Project\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\DevOps_Project\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\DevOps_Project\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\DevOps_Project\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\DevOps_Project\tests\UserModelTest.php(9): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): App\Tests\Models\UserModelTest->testDindAllUsers()
#8 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#9 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#10 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(App\Tests\Models\UserModelTest))
#11 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#12 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#13 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#14 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#15 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#16 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#17 C:\xampp\htdocs\DevOps_Project\vendor\bin\phpunit(122): include('C:\\xampp\\htdocs...')
#18 {main}
ERROR - 2025-04-25 17:40:56 --> Exception: no such table: db_user in C:\xampp\htdocs\DevOps_Project\system\Database\SQLite3\Connection.php:175
Stack trace:
#0 C:\xampp\htdocs\DevOps_Project\system\Database\SQLite3\Connection.php(175): SQLite3->exec('INSERT INTO `db...')
#1 C:\xampp\htdocs\DevOps_Project\system\Database\BaseConnection.php(738): CodeIgniter\Database\SQLite3\Connection->execute('INSERT INTO `db...')
#2 C:\xampp\htdocs\DevOps_Project\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `db...')
#3 C:\xampp\htdocs\DevOps_Project\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `db...', Array, false)
#4 C:\xampp\htdocs\DevOps_Project\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\DevOps_Project\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\DevOps_Project\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\DevOps_Project\tests\UserModelTest.php(16): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): App\Tests\Models\UserModelTest->testInsertUser()
#9 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#10 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#11 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(App\Tests\Models\UserModelTest))
#12 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#13 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#14 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#15 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#16 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#17 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#18 C:\xampp\htdocs\DevOps_Project\vendor\bin\phpunit(122): include('C:\\xampp\\htdocs...')
#19 {main}
ERROR - 2025-04-25 17:45:31 --> Exception: Unable to prepare statement: 1, no such table: db_user in C:\xampp\htdocs\DevOps_Project\system\Database\SQLite3\Connection.php:176
Stack trace:
#0 C:\xampp\htdocs\DevOps_Project\system\Database\SQLite3\Connection.php(176): SQLite3->query('SELECT *\nFROM `...')
#1 C:\xampp\htdocs\DevOps_Project\system\Database\BaseConnection.php(738): CodeIgniter\Database\SQLite3\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\DevOps_Project\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\DevOps_Project\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\DevOps_Project\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\DevOps_Project\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\DevOps_Project\tests\UserModelTest.php(9): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): App\Tests\Models\UserModelTest->testDindAllUsers()
#8 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#9 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#10 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(App\Tests\Models\UserModelTest))
#11 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#12 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#13 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#14 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#15 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#16 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#17 C:\xampp\htdocs\DevOps_Project\vendor\bin\phpunit(122): include('C:\\xampp\\htdocs...')
#18 {main}
ERROR - 2025-04-25 17:45:31 --> Exception: no such table: db_user in C:\xampp\htdocs\DevOps_Project\system\Database\SQLite3\Connection.php:175
Stack trace:
#0 C:\xampp\htdocs\DevOps_Project\system\Database\SQLite3\Connection.php(175): SQLite3->exec('INSERT INTO `db...')
#1 C:\xampp\htdocs\DevOps_Project\system\Database\BaseConnection.php(738): CodeIgniter\Database\SQLite3\Connection->execute('INSERT INTO `db...')
#2 C:\xampp\htdocs\DevOps_Project\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `db...')
#3 C:\xampp\htdocs\DevOps_Project\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `db...', Array, false)
#4 C:\xampp\htdocs\DevOps_Project\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\DevOps_Project\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\DevOps_Project\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\DevOps_Project\tests\UserModelTest.php(16): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): App\Tests\Models\UserModelTest->testInsertUser()
#9 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#10 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#11 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(App\Tests\Models\UserModelTest))
#12 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#13 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#14 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#15 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#16 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#17 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#18 C:\xampp\htdocs\DevOps_Project\vendor\bin\phpunit(122): include('C:\\xampp\\htdocs...')
#19 {main}
ERROR - 2025-04-25 17:56:52 --> Exception: Unable to prepare statement: 1, no such table: db_user in C:\xampp\htdocs\DevOps_Project\system\Database\SQLite3\Connection.php:176
Stack trace:
#0 C:\xampp\htdocs\DevOps_Project\system\Database\SQLite3\Connection.php(176): SQLite3->query('SELECT *\nFROM `...')
#1 C:\xampp\htdocs\DevOps_Project\system\Database\BaseConnection.php(738): CodeIgniter\Database\SQLite3\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\DevOps_Project\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\DevOps_Project\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\DevOps_Project\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\DevOps_Project\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\DevOps_Project\tests\UserModelTest.php(9): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): App\Tests\Models\UserModelTest->testDindAllUsers()
#8 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#9 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#10 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(App\Tests\Models\UserModelTest))
#11 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#12 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#13 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#14 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#15 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#16 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#17 C:\xampp\htdocs\DevOps_Project\vendor\bin\phpunit(122): include('C:\\xampp\\htdocs...')
#18 {main}
ERROR - 2025-04-25 17:56:52 --> Exception: no such table: db_user in C:\xampp\htdocs\DevOps_Project\system\Database\SQLite3\Connection.php:175
Stack trace:
#0 C:\xampp\htdocs\DevOps_Project\system\Database\SQLite3\Connection.php(175): SQLite3->exec('INSERT INTO `db...')
#1 C:\xampp\htdocs\DevOps_Project\system\Database\BaseConnection.php(738): CodeIgniter\Database\SQLite3\Connection->execute('INSERT INTO `db...')
#2 C:\xampp\htdocs\DevOps_Project\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `db...')
#3 C:\xampp\htdocs\DevOps_Project\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `db...', Array, false)
#4 C:\xampp\htdocs\DevOps_Project\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\DevOps_Project\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\DevOps_Project\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\DevOps_Project\tests\UserModelTest.php(16): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): App\Tests\Models\UserModelTest->testInsertUser()
#9 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#10 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#11 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(App\Tests\Models\UserModelTest))
#12 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#13 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#14 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#15 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#16 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#17 C:\xampp\htdocs\DevOps_Project\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#18 C:\xampp\htdocs\DevOps_Project\vendor\bin\phpunit(122): include('C:\\xampp\\htdocs...')
#19 {main}
